name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubunto-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
         dotnet-verion: '8.0.x'

      - name: Restore
        run: dotnet restore ./TestApp.sln

      - name: Build
        run: dotnet build ./TestApp.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./TestApp.sln --configuration Release --no-build
      
